# 2.2 数据操作

In [19]:
import torch 
import numpy as np

## 2.2.3 广播机制

In [2]:
x = torch.arange(1,3)
x

tensor([1, 2])

In [4]:
x = x.view(1,2)
x

tensor([[1, 2]])

In [5]:
y = torch.arange(1,4).view(3,1)
y

tensor([[1],
        [2],
        [3]])

In [6]:
x+y

tensor([[2, 3],
        [3, 4],
        [4, 5]])

## 2.2.5 Tensor和NumPy相互转换

In [7]:
# 使用numpy()将Tensor转换成NumPy数组:

a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [8]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [9]:
a+=1 
a

tensor([2., 2., 2., 2., 2.])

In [10]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [11]:
b+=1 
b

array([3., 3., 3., 3., 3.], dtype=float32)

In [12]:
a

tensor([3., 3., 3., 3., 3.])

In [13]:
# NumPy数组转
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [14]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [15]:
a+= 1
a

array([2., 2., 2., 2., 2.])

In [16]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [17]:
b+= 1
b

tensor([3., 3., 3., 3., 3.], dtype=torch.float64)

In [18]:
a

array([3., 3., 3., 3., 3.])

## 2.2.6 Tensor on GPU

In [21]:
torch.cuda.is_available()

False

In [23]:
device = torch.device('cuda')

device 

device(type='cuda')

In [24]:
x =x.to(device)

AssertionError: 
The NVIDIA driver on your system is too old (found version 8000).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

In [ ]:
# oh, I forget, I do not have a GPU 
# hahaha 