# lesson 19 感知机

In [4]:
import torch
import torch.nn.functional as F

In [3]:
x = torch.randn(1,10)
w = torch.randn(1,10, requires_grad = True)

o = torch.sigmoid(x@w.t())
o, o.shape 

(tensor([[0.9941]], grad_fn=<SigmoidBackward>), torch.Size([1, 1]))

In [5]:
loss = F.mse_loss(torch.ones(1), o)
loss, loss.shape 

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Using a target size (torch.Size([1, 1])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  """Entry point for launching an IPython kernel.


(tensor(3.5178e-05, grad_fn=<MeanBackward0>), torch.Size([]))

In [7]:
loss.backward()

In [8]:
w.grad

tensor([[ 1.2491e-04, -2.2095e-05, -6.8919e-05,  5.8731e-05, -1.0389e-04,
          4.5120e-05, -8.4262e-05,  7.7960e-05, -1.9852e-05,  6.1075e-06]])

##################################

In [10]:
x = torch.randn(1,10)
w = torch.randn(2,10, requires_grad =True)
x@w.t()

TypeError: matmul(): argument 'other' (position 1) must be Tensor, not torch.Size

In [14]:
a = x@w.t()
a.shape

torch.Size([1, 2])

In [16]:
o = torch.sigmoid(x@w.t())
o, o.shape 

(tensor([[0.8418, 0.8887]], grad_fn=<SigmoidBackward>), torch.Size([1, 2]))

In [17]:
loss = F.mse_loss(torch.ones(1,1), o)
loss

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Using a target size (torch.Size([1, 2])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  """Entry point for launching an IPython kernel.


tensor(0.0187, grad_fn=<MeanBackward0>)

In [18]:
o

tensor([[0.8418, 0.8887]], grad_fn=<SigmoidBackward>)

In [20]:
torch.ones(1)-o

tensor([[0.1582, 0.1113]], grad_fn=<SubBackward0>)

In [21]:
loss.backward()

In [22]:
w.grad

tensor([[ 0.0172,  0.0286, -0.0161, -0.0017,  0.0170,  0.0278, -0.0104,  0.0011,
          0.0154,  0.0365],
        [ 0.0090,  0.0149, -0.0084, -0.0009,  0.0089,  0.0145, -0.0054,  0.0006,
          0.0080,  0.0191]])