# Lesson8: 切片与索引

## indexing 

In [1]:
import numpy as np
import torch

In [26]:
a = torch.rand(4,3,28,28)
a

tensor([[[[6.6561e-02, 8.6423e-01, 2.7555e-01,  ..., 9.7316e-01,
           2.2671e-01, 9.1458e-01],
          [9.8637e-01, 5.9401e-01, 9.5105e-01,  ..., 8.1556e-01,
           3.4273e-01, 7.9043e-01],
          [7.9284e-01, 7.3338e-01, 7.6736e-03,  ..., 3.4356e-03,
           2.4967e-01, 8.5373e-01],
          ...,
          [4.0900e-01, 3.3828e-01, 7.7587e-01,  ..., 5.0629e-01,
           3.7400e-01, 8.5927e-01],
          [4.5232e-01, 6.9170e-01, 4.6732e-02,  ..., 2.7195e-01,
           9.2727e-04, 4.6565e-01],
          [6.0798e-01, 2.3270e-01, 4.2491e-01,  ..., 6.1173e-01,
           8.3222e-01, 7.3997e-01]],

         [[9.7291e-03, 1.9468e-01, 4.5779e-02,  ..., 6.7300e-01,
           9.5489e-01, 7.0948e-01],
          [5.4495e-01, 2.0435e-01, 4.0730e-01,  ..., 6.8927e-01,
           6.1975e-01, 9.3627e-04],
          [2.6472e-01, 5.2285e-01, 5.0467e-01,  ..., 2.8319e-01,
           6.7030e-01, 2.3765e-01],
          ...,
          [3.1910e-01, 6.0565e-01, 5.8562e-01,  ..., 4.9631

In [5]:
a.shape

torch.Size([4, 3, 28, 28])

In [6]:
a[0].shape

torch.Size([3, 28, 28])

In [8]:
a[0][0].shape

torch.Size([28, 28])

In [9]:
a[0,0].shape

torch.Size([28, 28])

In [10]:
a[0,0,2,4]

tensor(0.6039)

In [11]:
a[0]

tensor([[[0.6062, 0.7999, 0.8573,  ..., 0.4021, 0.0310, 0.7809],
         [0.8126, 0.0918, 0.8770,  ..., 0.2643, 0.1691, 0.4666],
         [0.3895, 0.1012, 0.1302,  ..., 0.9804, 0.0496, 0.8268],
         ...,
         [0.6452, 0.3837, 0.6535,  ..., 0.8970, 0.0113, 0.1590],
         [0.6315, 0.0801, 0.0606,  ..., 0.0335, 0.6950, 0.1411],
         [0.0446, 0.7795, 0.0537,  ..., 0.3576, 0.0919, 0.6052]],

        [[0.7934, 0.6603, 0.3149,  ..., 0.3018, 0.3730, 0.9257],
         [0.6490, 0.0672, 0.3927,  ..., 0.7682, 0.8206, 0.8130],
         [0.8378, 0.3612, 0.1582,  ..., 0.0068, 0.2344, 0.8902],
         ...,
         [0.9240, 0.1514, 0.6831,  ..., 0.9979, 0.3284, 0.4424],
         [0.1092, 0.0940, 0.6184,  ..., 0.0069, 0.1592, 0.7181],
         [0.6348, 0.2681, 0.1135,  ..., 0.5271, 0.0803, 0.1084]],

        [[0.4137, 0.8569, 0.6936,  ..., 0.9412, 0.2117, 0.4471],
         [0.5817, 0.6921, 0.4678,  ..., 0.0336, 0.5006, 0.3710],
         [0.6484, 0.8040, 0.4982,  ..., 0.4983, 0.4211, 0.

In [12]:
a[0][0]

tensor([[0.6062, 0.7999, 0.8573, 0.9876, 0.0199, 0.5248, 0.5730, 0.0362, 0.0030,
         0.7536, 0.4174, 0.4760, 0.9046, 0.2156, 0.2232, 0.7953, 0.8414, 0.0642,
         0.1518, 0.1744, 0.3162, 0.8188, 0.2779, 0.0869, 0.8280, 0.4021, 0.0310,
         0.7809],
        [0.8126, 0.0918, 0.8770, 0.4469, 0.4886, 0.9700, 0.6663, 0.2695, 0.1015,
         0.1090, 0.1289, 0.4086, 0.7360, 0.4071, 0.1359, 0.7412, 0.7386, 0.4595,
         0.3336, 0.8475, 0.0070, 0.6118, 0.0355, 0.9459, 0.6819, 0.2643, 0.1691,
         0.4666],
        [0.3895, 0.1012, 0.1302, 0.2081, 0.6039, 0.8168, 0.5257, 0.2814, 0.9123,
         0.5391, 0.2238, 0.5693, 0.0950, 0.0347, 0.5838, 0.0290, 0.3984, 0.5962,
         0.8619, 0.3289, 0.3369, 0.7130, 0.7797, 0.3304, 0.7214, 0.9804, 0.0496,
         0.8268],
        [0.5614, 0.8799, 0.3035, 0.3817, 0.3550, 0.2607, 0.1233, 0.3127, 0.0534,
         0.2035, 0.5618, 0.8382, 0.2497, 0.2047, 0.7161, 0.3823, 0.8199, 0.6962,
         0.2751, 0.0273, 0.8262, 0.6840, 0.0278, 0.4501

In [13]:
a[0][0][2]

tensor([0.3895, 0.1012, 0.1302, 0.2081, 0.6039, 0.8168, 0.5257, 0.2814, 0.9123,
        0.5391, 0.2238, 0.5693, 0.0950, 0.0347, 0.5838, 0.0290, 0.3984, 0.5962,
        0.8619, 0.3289, 0.3369, 0.7130, 0.7797, 0.3304, 0.7214, 0.9804, 0.0496,
        0.8268])

In [14]:
a[0][0][2].shape

torch.Size([28])

In [15]:
a[0][0][2][4]

tensor(0.6039)

## select first/ last N 

In [16]:
a.shape

torch.Size([4, 3, 28, 28])

In [17]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [18]:
a[:2,:1,:,:].shape

torch.Size([2, 1, 28, 28])

In [20]:
a[:2,1,:,:].shape

torch.Size([2, 28, 28])

In [21]:
a[:2,-1:,:,:].shape

torch.Size([2, 1, 28, 28])

In [24]:
a = [1,2,3,4,5,6]
a[-1:]

[6]

In [27]:
a[:,:,0:28:2, 0:28:2].shape

torch.Size([4, 3, 14, 14])

In [28]:
a[:,:,::2,::2].shape

torch.Size([4, 3, 14, 14])

In [29]:
a[:,:,::1,::1].shape

torch.Size([4, 3, 28, 28])

## select by specific index 

In [30]:
a.shape

torch.Size([4, 3, 28, 28])

In [34]:
index = torch.tensor([0,2], dtype=torch.long)

In [36]:
a.index_select(0,index).shape

# 选择 0 维度 的 0， 2 这两个

torch.Size([2, 3, 28, 28])

In [37]:
idx = torch.tensor([0,1], dtype= torch.long)
a.index_select(1, idx).shape

torch.Size([4, 2, 28, 28])

In [38]:
a.index_select(2, torch.arange(28)).shape

torch.Size([4, 3, 28, 28])

In [39]:
a.index_select(2, torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

### ...

In [40]:
a.shape

torch.Size([4, 3, 28, 28])

In [41]:
a[...].shape

torch.Size([4, 3, 28, 28])

In [42]:
a[0,...].shape

torch.Size([3, 28, 28])

In [43]:
a[:, 1, ...].shape

torch.Size([4, 28, 28])

In [44]:
a[...,:2].shape

torch.Size([4, 3, 28, 2])

## select by mask 

- 不想看

## select by flattern index 

In [45]:
src = torch.tensor([[4,3,5],
                   [6,7,8]])
src

tensor([[4, 3, 5],
        [6, 7, 8]])

In [46]:
torch.take(src, torch.tensor([0,2,5]))

tensor([4, 5, 8])