# lesson 9 Tensor 维度变换 Expand 

In [1]:
import numpy as np 
import torch

## Operation 
- view/ reshape 

- squeeze/unsqueeze 

- transpose/t/permute 

- expand / repeat 

### view/ reshape 

- lost dim information 

In [3]:
a = torch.rand(4,1,28,28)
a.shape

torch.Size([4, 1, 28, 28])

In [5]:
a.view(4,28*28).shape 

torch.Size([4, 784])

In [6]:
a.view(4*28,28).shape 

torch.Size([112, 28])

In [7]:
a.view(4*1, 28,28).shape 

torch.Size([4, 28, 28])

In [9]:
b = a.view(4,28*28)
b.shape 

torch.Size([4, 784])

b.view(4,28,28,1)  # 可以做 但是逻辑错误

In [11]:
b.view(4,28,28,1) 

tensor([[[[0.2561],
          [0.8799],
          [0.1103],
          ...,
          [0.8982],
          [0.9602],
          [0.0671]],

         [[0.2621],
          [0.3227],
          [0.9826],
          ...,
          [0.5878],
          [0.0209],
          [0.3398]],

         [[0.2677],
          [0.6541],
          [0.5226],
          ...,
          [0.4412],
          [0.2229],
          [0.5391]],

         ...,

         [[0.8199],
          [0.0446],
          [0.1626],
          ...,
          [0.6217],
          [0.2847],
          [0.4418]],

         [[0.7357],
          [0.6631],
          [0.8583],
          ...,
          [0.5017],
          [0.6484],
          [0.8358]],

         [[0.5291],
          [0.6225],
          [0.5380],
          ...,
          [0.7112],
          [0.1651],
          [0.4647]]],


        [[[0.8730],
          [0.0901],
          [0.1044],
          ...,
          [0.8500],
          [0.4838],
          [0.8880]],

         [[0.5226],
    

## flexible but prone to corrupt 

In [12]:
a.shape 

torch.Size([4, 1, 28, 28])

In [13]:
a.view(783)

RuntimeError: shape '[783]' is invalid for input of size 3136

## squezz vs unsqueeze 

### unsqueeze 

- [-a.dim()-1, a.dim()+1)  

In [14]:
a.shape 

torch.Size([4, 1, 28, 28])

In [15]:
a.unsqueeze(0).shape 

torch.Size([1, 4, 1, 28, 28])

In [16]:
a.unsqueeze(-1).shape 

torch.Size([4, 1, 28, 28, 1])

In [17]:
a.shape 

torch.Size([4, 1, 28, 28])

In [18]:
a.unsqueeze(4).shape 

torch.Size([4, 1, 28, 28, 1])

In [19]:
a.unsqueeze(-4).shape 

torch.Size([4, 1, 1, 28, 28])

In [21]:
a.unsqueeze(-5).shape 

torch.Size([1, 4, 1, 28, 28])

In [22]:
a = torch.tensor([1.2, 2.3])
a.shape 

torch.Size([2])

In [23]:
a.unsqueeze(-1).shape 

torch.Size([2, 1])

In [25]:
a

tensor([1.2000, 2.3000])

In [26]:
a.unsqueeze(-1)

tensor([[1.2000],
        [2.3000]])

In [28]:
a.unsqueeze(0).shape

torch.Size([1, 2])

In [29]:
a.unsqueeze(0)

tensor([[1.2000, 2.3000]])

### for example 

In [42]:
b = torch.rand(32)

f = torch.rand(4,32,14,14)

b.shape, f.shape 

(torch.Size([32]), torch.Size([4, 32, 14, 14]))

In [43]:
b = b.unsqueeze(1)  # [32,1]
b.shape

torch.Size([32, 1])

In [44]:
b = b.unsqueeze(2) # [32,1,1]

In [45]:
b = b.unsqueeze(0) #[1,32,1,1]

In [46]:
b.shape

torch.Size([1, 32, 1, 1])

(b+f).shape  # BROADCASTING 

In [49]:
(b+f).shape 

torch.Size([4, 32, 14, 14])

### squeeze 

In [50]:
b.shape 

torch.Size([1, 32, 1, 1])

In [51]:
b.squeeze().shape 

torch.Size([32])

In [52]:
b.squeeze(0).shape 

torch.Size([32, 1, 1])

In [53]:
b.squeeze(-1).shape 

torch.Size([1, 32, 1])

In [54]:
b.shape

torch.Size([1, 32, 1, 1])

In [55]:
b.squeeze(1).shape 

torch.Size([1, 32, 1, 1])

In [56]:
b.squeeze(-4).shape 

torch.Size([32, 1, 1])

### expand /repeat

- expand: broadcasting 

- memory copied 

In [57]:
a = torch.rand(4,32,14,14)

b.shape 

torch.Size([1, 32, 1, 1])

In [58]:
b.expand(4,32,14,14).shape 

torch.Size([4, 32, 14, 14])

In [69]:
b.expand(2,64,2,2).shape 

RuntimeError: The expanded size of the tensor (64) must match the existing size (32) at non-singleton dimension 1.  Target sizes: [2, 64, 2, 2].  Tensor sizes: [1, 32, 1, 1]

In [67]:
b.shape 

torch.Size([1, 32, 1, 1])

In [68]:
b.expand(-1,32,-1,-1).shape 

torch.Size([1, 32, 1, 1])

In [70]:
b.expand(-1,32,-1,-4).shape

# -4 只是一个 bug -4 没有意义

torch.Size([1, 32, 1, -4])

### repeat 

- memory touched 

In [71]:
b.shape 

torch.Size([1, 32, 1, 1])

In [72]:
b.repeat(4,32,1,1).shape 

torch.Size([4, 1024, 1, 1])

In [74]:
b.repeat(6,8,8,8).shape

torch.Size([6, 256, 8, 8])

In [75]:
b.repeat(4,1,1,1).shape 

torch.Size([4, 32, 1, 1])

In [76]:
b.repeat(4,1,32,32).shape 

torch.Size([4, 32, 32, 32])

### .t()

In [77]:
b.shape 

torch.Size([1, 32, 1, 1])

In [78]:
b.t()

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 4D

In [79]:
c = torch.rand(8,9)
c.shape 

torch.Size([8, 9])

In [80]:
c.t().shape

torch.Size([9, 8])

In [81]:
d = torch.randn(3,4)
d.t().shape

torch.Size([4, 3])

### transpose 

In [84]:
a = torch.rand(4,3,32,32)
a.shape 

torch.Size([4, 3, 32, 32])

In [ ]:
dim: 0 1 2 3  
     4 3 32 32
     b c h w
-> transpose(1,3) 
     b w h c 
    4 32 32 3 

In [86]:
a1 = a.transpose(1,3).view(4, 32*32*3).view(4,3,32,32)
a1

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [89]:
a1 = a.transpose(1,3).contiguous().view(4, 32*32*3).view(4,3,32,32)
a1.shape 

torch.Size([4, 3, 32, 32])

In [90]:
a2 = a.transpose(1,3).contiguous().view(4*32*32*3).view(4,32,32,3).transpose(1,3)
a2.shape 

torch.Size([4, 3, 32, 32])

In [91]:
torch.all(torch.eq(a,a1))

tensor(False)

In [92]:
torch.all(torch.eq(a,a2))

tensor(True)

### permute 

In [94]:
a = torch.rand(4,3,28,28)
a.shape 

torch.Size([4, 3, 28, 28])

In [95]:
a.transpose(1,3).shape 

torch.Size([4, 28, 28, 3])

In [96]:
b = torch.rand(4,3,28,32)
b.shape 

torch.Size([4, 3, 28, 32])

In [97]:
b.transpose(1,3).shape

torch.Size([4, 32, 28, 3])

In [98]:
b.transpose(1,3).transpose(1,2).shape 

torch.Size([4, 28, 32, 3])

In [99]:
b.permute(0,2,3,1).shape 

torch.Size([4, 28, 32, 3])

In [ ]:
4 3 28 32 
-> permute(0,2,3,1)
4, 28, 32 3