# lesson 6  基本数据类型

In [22]:
import torch 
import numpy as np

In [2]:
a = torch.randn(2,3)
a

tensor([[ 0.3544,  0.1709,  0.9585],
        [ 2.5448, -0.1973, -1.4519]])

In [3]:
a.type()

'torch.FloatTensor'

In [4]:
type(a)

torch.Tensor

In [5]:
isinstance(a, torch.FloatTensor)

True

In [8]:
data = torch.randn(2,3, dtype= torch.double)
data

tensor([[ 0.3329, -0.0838, -1.0901],
        [ 1.1839, -1.1950, -0.4444]], dtype=torch.float64)

In [10]:
data.type()

'torch.DoubleTensor'

## Dim 0 

In [11]:
torch.tensor(1.)

tensor(1.)

In [12]:
torch.tensor(1.3)

tensor(1.3000)

In [13]:
a = torch.tensor(2.2)
a.shape

torch.Size([])

In [14]:
len(a.shape)

0

In [15]:
a.size()

torch.Size([])

## Dim 1

In [16]:
a = torch.tensor([1.1])

tensor([1.1000])

In [17]:
torch.tensor([1.1,1.2])

tensor([1.1000, 1.2000])

In [19]:
torch.tensor(1, dtype = torch.double)

tensor(1., dtype=torch.float64)

In [20]:
torch.FloatTensor(1)

tensor([0.])

In [21]:
torch.FloatTensor(2)

tensor([0., 0.])

## Dim 3 

In [23]:
a = torch.randn(1,2,3)
a

tensor([[[ 0.1791,  0.0976, -0.8936],
         [ 1.4796,  0.7681,  0.9371]]])

In [24]:
a.shape

torch.Size([1, 2, 3])

In [25]:
a.shape[0]

1

In [26]:
a[0]

tensor([[ 0.1791,  0.0976, -0.8936],
        [ 1.4796,  0.7681,  0.9371]])

In [27]:
a = torch.rand(2,3,28,28)
a

tensor([[[[0.5620, 0.4548, 0.5465,  ..., 0.0196, 0.8359, 0.2862],
          [0.3770, 0.8611, 0.7168,  ..., 0.1705, 0.9073, 0.3489],
          [0.9369, 0.5601, 0.6770,  ..., 0.3825, 0.9586, 0.9401],
          ...,
          [0.8045, 0.4945, 0.8930,  ..., 0.9885, 0.8943, 0.9748],
          [0.0228, 0.2142, 0.7848,  ..., 0.4961, 0.0548, 0.5792],
          [0.2378, 0.5701, 0.1542,  ..., 0.7327, 0.1000, 0.0778]],

         [[0.9324, 0.0214, 0.2533,  ..., 0.5055, 0.9558, 0.6226],
          [0.6515, 0.5819, 0.7364,  ..., 0.8814, 0.9545, 0.8519],
          [0.9655, 0.5364, 0.8449,  ..., 0.1912, 0.4461, 0.2962],
          ...,
          [0.8200, 0.9156, 0.2767,  ..., 0.6573, 0.6815, 0.4487],
          [0.3357, 0.4221, 0.3622,  ..., 0.1175, 0.3896, 0.0068],
          [0.3055, 0.2065, 0.3255,  ..., 0.2163, 0.4837, 0.6043]],

         [[0.3352, 0.0622, 0.9027,  ..., 0.5494, 0.4035, 0.0629],
          [0.1212, 0.6419, 0.3401,  ..., 0.3344, 0.3094, 0.9543],
          [0.9186, 0.1003, 0.8511,  ..., 0

In [28]:
a.shape 

torch.Size([2, 3, 28, 28])

In [30]:
a.numel()

4704

In [31]:
a.dim()

4

In [32]:
a = torch.tensor(1)
a

tensor(1)

In [33]:
a.dim()

0