# lesson 12 基本运算

- add / minus/ multiply / divide

- matmul

- pow 

- sqrt / rsqrt 

- round 

In [1]:
import numpy as np 
import torch

## basic 

In [2]:
a = torch.rand(3,4)
b = torch.rand(4)

In [4]:
a

tensor([[0.3331, 0.3392, 0.3684, 0.2179],
        [0.7933, 0.7740, 0.1242, 0.8029],
        [0.5352, 0.8370, 0.3539, 0.7055]])

In [5]:
b

tensor([0.3792, 0.3125, 0.0525, 0.9945])

In [6]:
a+b

tensor([[0.7123, 0.6518, 0.4208, 1.2124],
        [1.1725, 1.0866, 0.1767, 1.7973],
        [0.9144, 1.1495, 0.4064, 1.7000]])

In [7]:
torch.add(a,b)

tensor([[0.7123, 0.6518, 0.4208, 1.2124],
        [1.1725, 1.0866, 0.1767, 1.7973],
        [0.9144, 1.1495, 0.4064, 1.7000]])

In [8]:
torch.all(torch.eq(a-b, torch.sub(a,b)))

tensor(True)

In [11]:
torch.all(torch.eq(a*b, torch.mul(a,b)))

tensor(True)

In [13]:
torch.all(torch.eq(a/b , torch.div(a,b)))

tensor(True)

## matmul

- torch.mm  only for 2d 

- torch.matmul

In [14]:
a = torch.full([2,2],3)
a

tensor([[3., 3.],
        [3., 3.]])

In [15]:
b = torch.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [16]:
torch.mm(a,b)

tensor([[6., 6.],
        [6., 6.]])

In [17]:
torch.matmul(a,b)

tensor([[6., 6.],
        [6., 6.]])

In [18]:
a@b

tensor([[6., 6.],
        [6., 6.]])

## an example 

In [19]:
a = torch.rand(4,784)
x = torch.rand(4,784)
w = torch.rand(512,784)

In [21]:
(x@w.t()).shape 

torch.Size([4, 512])

## > 2d tensor matmul?

In [22]:
a= torch.rand(4,3,28,64)
b = torch.rand(4,3,64,32)

In [23]:
torch.mm(a,b).shape 

RuntimeError: matrices expected, got 4D, 4D tensors at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensorMath.cpp:192

In [24]:
torch.matmul(a,b).shape 

torch.Size([4, 3, 28, 32])

## power 

In [25]:
a = torch.full([2,2], 3)
a

tensor([[3., 3.],
        [3., 3.]])

In [26]:
a.pow(2)

tensor([[9., 9.],
        [9., 9.]])

In [27]:
a**2

tensor([[9., 9.],
        [9., 9.]])

In [28]:
a**3

tensor([[27., 27.],
        [27., 27.]])

In [29]:
a**4

tensor([[81., 81.],
        [81., 81.]])

In [31]:
aa = a**2
aa

tensor([[9., 9.],
        [9., 9.]])

In [32]:
aa.sqrt()

tensor([[3., 3.],
        [3., 3.]])

In [35]:
b = torch.full([3,3], 16)
b

tensor([[16., 16., 16.],
        [16., 16., 16.],
        [16., 16., 16.]])

In [36]:
b.rsqrt()  # 平方根倒数

tensor([[0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500]])

In [37]:
aa**(0.5)

tensor([[3., 3.],
        [3., 3.]])

## exp log 

In [38]:
a = torch.exp(torch.ones(2,2))
a

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [39]:
torch.log(a)

tensor([[1., 1.],
        [1., 1.]])

## approximation 

- .floor()  .ceil()

- .round()

- .trunc()  .frac()

In [40]:
a = torch.tensor(3.14)
a

tensor(3.1400)

In [41]:
a.floor()

tensor(3.)

In [42]:
a.ceil()

tensor(4.)

In [43]:
a.trunc()

tensor(3.)

In [44]:
a.frac()

tensor(0.1400)

In [45]:
a = torch.tensor(3.499)
a

tensor(3.4990)

In [46]:
a.round()

tensor(3.)

In [50]:
a = torch.tensor(3.5)
a.round()

tensor(4.)

## clamp 

In [51]:
grad = torch.rand(2,3)*15 
grad


tensor([[ 4.8028,  6.5006,  3.7124],
        [14.8633,  6.2878, 11.7441]])

In [52]:
grad.max()

tensor(14.8633)

In [53]:
grad.median()

tensor(6.2878)

In [55]:
grad

tensor([[ 4.8028,  6.5006,  3.7124],
        [14.8633,  6.2878, 11.7441]])

In [54]:
grad.clamp(10)

tensor([[10.0000, 10.0000, 10.0000],
        [14.8633, 10.0000, 11.7441]])

In [56]:
grad.clamp(0,10)

tensor([[ 4.8028,  6.5006,  3.7124],
        [10.0000,  6.2878, 10.0000]])