# lesson7 创建 Tensor 

In [1]:
import torch 
import numpy as np 

## import from numpy 

In [2]:
a = np.array([2,3.3])
a

array([2. , 3.3])

In [3]:
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [4]:
a = np.ones([2,3])
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

## import from List 

In [9]:
a = torch.tensor([2, 3.2])
a

tensor([2.0000, 3.2000])

In [10]:
a.shape

torch.Size([2])

In [12]:
a.dim()

1

In [14]:
b = torch.tensor([[2, 3.2],
             [1,22.3]])
b

tensor([[ 2.0000,  3.2000],
        [ 1.0000, 22.3000]])

In [15]:
b.shape

torch.Size([2, 2])

In [16]:
b.dim()

2

## uninitialized 

- torch.empty()

- torch.FloatTensor(d1, d2, d3) != torch.tensor(d1, d2, d3)

- torch.IntTensor(d1, d2, d3)

In [17]:
a = torch.empty(1)

tensor([0.])

In [18]:
a.type()

'torch.FloatTensor'

In [19]:
a = torch.empty(6)
a

tensor([1.0010e-38, 9.0918e-39, 1.0102e-38, 1.0194e-38, 2.9389e-39, 9.6429e-39])

In [20]:
a = torch.empty(2,3)
a

tensor([[5.3184e+22, 1.2915e-11, 8.4078e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])

In [21]:
torch.Tensor(2,3)

tensor([[1.1039e-05, 1.0871e-05, 3.2504e+21],
        [1.0503e-05, 1.7298e-04, 1.0487e+21]])

In [22]:
torch.IntTensor(2,3)

tensor([[1717644644, 1714237749,  912339768],
        [ 808726625,  775250738, 1952543859]], dtype=torch.int32)

In [23]:
torch.FloatTensor(2,3)

tensor([[1.0010e-38, 9.0918e-39, 1.0102e-38],
        [1.0194e-38, 2.9389e-39, 9.6429e-39]])

## set default type 

In [24]:
torch.tensor([1.2, 3]).type()

'torch.FloatTensor'

#### set_default_tensor_type

In [25]:
torch.set_default_tensor_type(torch.DoubleTensor)

In [26]:
torch.tensor([1.2, 3]).type()

'torch.DoubleTensor'

### rand/rand_like, randint 

In [27]:
torch.rand(3,3)

tensor([[0.5937, 0.1763, 0.5080],
        [0.6944, 0.1369, 0.8483],
        [0.6343, 0.4518, 0.3159]])

In [29]:
a = torch.rand(3,3)
a

tensor([[0.6750, 0.4439, 0.2169],
        [0.6173, 0.1164, 0.4714],
        [0.4718, 0.2971, 0.1394]])

In [30]:
torch.rand_like(a)

tensor([[0.9286, 0.1089, 0.4538],
        [0.6040, 0.8661, 0.0040],
        [0.9793, 0.3037, 0.1583]])

In [32]:
torch.randint(1,10,(3,3))

tensor([[4, 4, 1],
        [1, 5, 1],
        [9, 5, 9]])

### randn

- Note: randn()   ~ N(0,1)

- Note: N(mu, std)

In [33]:
torch.normal(mean= torch.full([10],0), std = torch.arange(1,0,-0.1))

tensor([-0.4784, -0.5156,  0.4660,  0.0234, -0.7840, -0.0617, -0.2442,  0.1890,
        -0.1720, -0.0939])

In [34]:
torch.normal(mean = torch.full([10],0), std = torch.arange(1,0,-0.1))

tensor([-0.3900, -1.0780, -1.4048, -1.5482,  1.1217,  0.0371,  0.2134,  0.4032,
         0.0933, -0.2469])

### full

In [36]:
torch.full([2,3],7)

tensor([[7., 7., 7.],
        [7., 7., 7.]])

In [37]:
torch.full([],7)

tensor(7.)

In [38]:
torch.full([1],7)

tensor([7.])

### arange/range

In [39]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [41]:
torch.range(0,10)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### linspace/ logspace 

In [42]:
torch.linspace(0,10, 4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [43]:
torch.linspace(0,10,steps=4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [44]:
torch.linspace(0,10, steps=9)

tensor([ 0.0000,  1.2500,  2.5000,  3.7500,  5.0000,  6.2500,  7.5000,  8.7500,
        10.0000])

In [45]:
torch.linspace(0,10,11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [46]:
torch.logspace(0,-1, steps=10)  # 10**n  power()

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

In [47]:
torch.logspace(0,1,steps=10)

tensor([ 1.0000,  1.2915,  1.6681,  2.1544,  2.7826,  3.5938,  4.6416,  5.9948,
         7.7426, 10.0000])

### ones/ zeros/ eye 

In [48]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [49]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [50]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [51]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [52]:
a = torch.zeros(3,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [53]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### randperm

- random.shuffle

In [56]:
torch.randperm(10)

tensor([0, 5, 3, 1, 6, 8, 7, 2, 9, 4])

In [54]:
a = torch.rand(2,3)
a

tensor([[0.6220, 0.8276, 0.2927],
        [0.2908, 0.7834, 0.5591]])

In [55]:
b = torch.rand(2,2)
b

tensor([[0.8271, 0.4201],
        [0.2536, 0.0800]])

In [60]:
idx = torch.randperm(2)
idx

tensor([1, 0])

In [61]:
a

tensor([[0.6220, 0.8276, 0.2927],
        [0.2908, 0.7834, 0.5591]])

In [63]:
a[1], a[0]

(tensor([0.2908, 0.7834, 0.5591]), tensor([0.6220, 0.8276, 0.2927]))

In [64]:
a[idx]

tensor([[0.2908, 0.7834, 0.5591],
        [0.6220, 0.8276, 0.2927]])

In [65]:
b[0],b[1]

(tensor([0.8271, 0.4201]), tensor([0.2536, 0.0800]))

In [66]:
b[idx]

tensor([[0.2536, 0.0800],
        [0.8271, 0.4201]])