# 随机梯度下降

In [ ]:
https://www.bilibili.com/video/av82458106?p=23
    
梯度的方向是函数值增加最快的方向

# P25. 常见梯度

# P26. 激活函数及其梯度1

In [1]:
import torch

In [2]:
a = torch.linspace(-100,100,10)
a

tensor([-100.0000,  -77.7778,  -55.5556,  -33.3333,  -11.1111,   11.1111,
          33.3333,   55.5555,   77.7778,  100.0000])

In [3]:
torch.sigmoid(a)

tensor([0.0000e+00, 1.6655e-34, 7.4564e-25, 3.3382e-15, 1.4945e-05, 9.9999e-01,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00])

In [4]:
a = torch.linspace(-1,1,10)
a

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])

In [5]:
torch.tanh(a)

tensor([-0.7616, -0.6514, -0.5047, -0.3215, -0.1107,  0.1107,  0.3215,  0.5047,
         0.6514,  0.7616])

### Relu 

In [6]:
from torch.nn import functional as F

In [7]:
a = torch.linspace(-1,1,10)

torch.relu(a)

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1111, 0.3333, 0.5556, 0.7778,
        1.0000])

In [8]:
F.relu(a)

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1111, 0.3333, 0.5556, 0.7778,
        1.0000])

In [6]:
from torch.nn import functional as F

# P27. Loss 以及梯度

autograd.grad 

In [3]:
x = torch.ones(1)
x

tensor([1.])

In [5]:
w = torch.full([1],2)
w

tensor([2.])

In [8]:
mse = F.mse_loss(torch.ones(1), x*w)

In [9]:
mse

tensor(1.)

In [10]:
torch.autograd.grad(mse,[w])

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [11]:
w.requires_grad_()

tensor([2.], requires_grad=True)

In [12]:
torch.autograd.grad(mse, [w])

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [14]:
mse = F.mse_loss(torch.ones(1), x*w)
mse

tensor(1., grad_fn=<MeanBackward0>)

In [15]:
torch.autograd.grad(mse, [w])

(tensor([2.]),)

### loss.backward 

In [16]:
w.requires_grad_()

tensor([2.], requires_grad=True)

In [18]:
mse = F.mse_loss(torch.ones(1), x*w)
mse.backward()

In [19]:
w.grad

tensor([2.])

In [20]:
w.grad.norm

<bound method Tensor.norm of tensor([2.])>

# P28. 激活函数及其梯度3

In [21]:
a = torch.rand(3)
a.requires_grad_()

tensor([0.9483, 0.6768, 0.5080], requires_grad=True)

In [22]:
p = F.softmax(a, dim=0)
p.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [29]:
p.backward(retain_graph=True)

RuntimeError: grad can be implicitly created only for scalar outputs

In [24]:
p = F.softmax(a, dim=0)
p

tensor([0.4156, 0.3168, 0.2676], grad_fn=<SoftmaxBackward>)

In [25]:
p[0]

tensor(0.4156, grad_fn=<SelectBackward>)

In [26]:
p[1]

tensor(0.3168, grad_fn=<SelectBackward>)

In [27]:
torch.autograd.grad(p[1], [a], retain_graph=True)

(tensor([-0.1317,  0.2164, -0.0848]),)

In [28]:
torch.autograd.grad(p[2],[a])

(tensor([-0.1112, -0.0848,  0.1960]),)

In [30]:
a = torch.rand(3)
a.requires_grad_()

tensor([0.4681, 0.6287, 0.3821], requires_grad=True)

In [31]:
p = F.softmax(a, dim=0)
p

tensor([0.3234, 0.3798, 0.2968], grad_fn=<SoftmaxBackward>)

In [33]:
p.backward(retain_graph=True)

RuntimeError: grad can be implicitly created only for scalar outputs

In [34]:
[a]

[tensor([0.4681, 0.6287, 0.3821], requires_grad=True)]

In [35]:
p[1]

tensor(0.3798, grad_fn=<SelectBackward>)

In [36]:
torch.autograd.grad(p[1],a, retain_graph=True)

(tensor([-0.1228,  0.2355, -0.1127]),)

In [37]:
torch.autograd.grad(p[1],[a], retain_graph=True)

(tensor([-0.1228,  0.2355, -0.1127]),)