# 1. PyTorch 介绍

In [1]:
import torch
from torch import autograd 

In [3]:
x = torch.tensor(1.)
a = torch.tensor(1., requires_grad=True)
b = torch.tensor(2., requires_grad=True)
c = torch.tensor(3., requires_grad=True)

In [4]:
y =a**2*x+b*x+c

In [6]:
print('before: ',a.grad, b.grad, c.grad)

before:  None None None


In [7]:
grads = autograd.grad(y, [a,b,c])
print('after: ', grads[0], grads[1], grads[2])

after:  tensor(2.) tensor(1.) tensor(1.)


In [8]:
grads

(tensor(2.), tensor(1.), tensor(1.))

# 3-5. 梯度下降 Linear  Regression 

# P12 切片与索引

In [2]:
import torch

In [3]:

a = torch.rand(4,3,28,28)
a

tensor([[[[0.6419, 0.5770, 0.2697,  ..., 0.2854, 0.3652, 0.5874],
          [0.9008, 0.9497, 0.3929,  ..., 0.6573, 0.4931, 0.8473],
          [0.5575, 0.9795, 0.4557,  ..., 0.4663, 0.7557, 0.1132],
          ...,
          [0.9116, 0.2249, 0.6768,  ..., 0.8053, 0.7042, 0.9425],
          [0.8743, 0.9181, 0.7897,  ..., 0.6105, 0.6833, 0.4863],
          [0.1126, 0.5789, 0.1738,  ..., 0.8348, 0.8666, 0.5532]],

         [[0.8909, 0.6562, 0.3898,  ..., 0.7510, 0.4300, 0.9281],
          [0.1553, 0.3632, 0.3960,  ..., 0.9956, 0.2950, 0.7485],
          [0.2251, 0.1557, 0.6432,  ..., 0.6215, 0.6503, 0.5672],
          ...,
          [0.8073, 0.0465, 0.6450,  ..., 0.3217, 0.1687, 0.0619],
          [0.2563, 0.2963, 0.8936,  ..., 0.9333, 0.9921, 0.6217],
          [0.3514, 0.9667, 0.6827,  ..., 0.7114, 0.4253, 0.4917]],

         [[0.9070, 0.4722, 0.2463,  ..., 0.8982, 0.7586, 0.0469],
          [0.8356, 0.8818, 0.9607,  ..., 0.0242, 0.4337, 0.7929],
          [0.8529, 0.0882, 0.1449,  ..., 0

In [4]:
a[0].shape

torch.Size([3, 28, 28])

In [5]:
a[0,0]

tensor([[0.6419, 0.5770, 0.2697, 0.3229, 0.8099, 0.5410, 0.0936, 0.8537, 0.9462,
         0.1418, 0.0041, 0.3783, 0.8363, 0.6898, 0.3993, 0.3799, 0.7148, 0.5093,
         0.5710, 0.9072, 0.0907, 0.9081, 0.2958, 0.8329, 0.5539, 0.2854, 0.3652,
         0.5874],
        [0.9008, 0.9497, 0.3929, 0.3514, 0.6611, 0.7320, 0.1529, 0.9633, 0.8038,
         0.6713, 0.4728, 0.9087, 0.0049, 0.5618, 0.1232, 0.3606, 0.0305, 0.8896,
         0.8756, 0.3673, 0.9890, 0.0554, 0.2071, 0.3914, 0.1579, 0.6573, 0.4931,
         0.8473],
        [0.5575, 0.9795, 0.4557, 0.0947, 0.1291, 0.8644, 0.5156, 0.5341, 0.3505,
         0.2841, 0.1037, 0.6303, 0.7085, 0.2664, 0.2013, 0.5752, 0.9305, 0.0669,
         0.3064, 0.4563, 0.2720, 0.0449, 0.3673, 0.1096, 0.6886, 0.4663, 0.7557,
         0.1132],
        [0.6232, 0.6785, 0.0842, 0.8511, 0.1758, 0.5922, 0.6301, 0.9754, 0.1314,
         0.0376, 0.2811, 0.1221, 0.6470, 0.0106, 0.6502, 0.3608, 0.0692, 0.7702,
         0.4653, 0.3700, 0.1394, 0.1236, 0.3820, 0.1854

In [6]:
a[0,0].shape

torch.Size([28, 28])

In [7]:
a[0,0,2,4]

tensor(0.1291)

## select firsst/last N 

In [8]:
a.shape

torch.Size([4, 3, 28, 28])

In [10]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [11]:
a[:2, :1,:,:].shape

torch.Size([2, 1, 28, 28])

In [12]:
a[:2, -1:,:,:].shape

torch.Size([2, 1, 28, 28])

In [15]:
a.shape

torch.Size([4, 3, 28, 28])

In [14]:
a[:2,1:,:,:].shape

torch.Size([2, 2, 28, 28])

##  select by steps 

In [16]:
a[:,:,0:28:2, 0:28:2].shape

torch.Size([4, 3, 14, 14])

In [17]:
a[:,:,::2,::2].shape

torch.Size([4, 3, 14, 14])

# P13. 索引与切片2

## select by steps 

In [18]:
a.shape

torch.Size([4, 3, 28, 28])

In [19]:
a[:,:,0:28:2, 0:28:2].shape

torch.Size([4, 3, 14, 14])

## select by specific index 

In [20]:
a.shape

torch.Size([4, 3, 28, 28])

torch.index_select(input, dim, index, out=None) → Tensor

In [28]:
indices=torch.LongTensor([0,2])
torch.index_select(a,0, indices).shape

torch.Size([2, 3, 28, 28])

In [ ]:
>>> x = torch.randn(3, 4)
>>> x

 1.2045  2.4084  0.4001  1.1372
 0.5596  1.5677  0.6219 -0.7954
 1.3635 -1.2313 -0.5414 -1.8478
[torch.FloatTensor of size 3x4]

>>> indices = torch.LongTensor([0, 2])
>>> torch.index_select(x, 0, indices)

 1.2045  2.4084  0.4001  1.1372
 1.3635 -1.2313 -0.5414 -1.8478
[torch.FloatTensor of size 2x4]

>>> torch.index_select(x, 1, indices)

 1.2045  0.4001
 0.5596  0.6219
 1.3635 -0.5414
[torch.FloatTensor of size 3x2]

In [30]:
torch.index_select(a, 1, indices).shape

torch.Size([4, 2, 28, 28])

In [32]:
torch.index_select(a,2, indices).shape

torch.Size([4, 3, 2, 28])

In [35]:
torch.index_select(a,2, torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

In [38]:
b= torch.rand(2,2,3,4)
b

tensor([[[[0.0518, 0.3707, 0.6357, 0.5651],
          [0.7455, 0.8993, 0.8996, 0.5205],
          [0.0416, 0.7480, 0.8813, 0.3289]],

         [[0.4246, 0.1962, 0.9842, 0.0630],
          [0.8791, 0.1710, 0.6632, 0.0837],
          [0.3168, 0.9068, 0.7597, 0.6429]]],


        [[[0.2603, 0.9811, 0.4213, 0.9594],
          [0.7628, 0.5062, 0.8340, 0.0782],
          [0.4589, 0.2107, 0.5254, 0.8221]],

         [[0.2604, 0.0350, 0.9136, 0.1961],
          [0.8171, 0.8297, 0.1995, 0.0871],
          [0.5602, 0.0249, 0.6280, 0.9933]]]])

In [39]:
indices = torch.LongTensor([0,1])
torch.index_select(b,0,indices)

tensor([[[[0.0518, 0.3707, 0.6357, 0.5651],
          [0.7455, 0.8993, 0.8996, 0.5205],
          [0.0416, 0.7480, 0.8813, 0.3289]],

         [[0.4246, 0.1962, 0.9842, 0.0630],
          [0.8791, 0.1710, 0.6632, 0.0837],
          [0.3168, 0.9068, 0.7597, 0.6429]]],


        [[[0.2603, 0.9811, 0.4213, 0.9594],
          [0.7628, 0.5062, 0.8340, 0.0782],
          [0.4589, 0.2107, 0.5254, 0.8221]],

         [[0.2604, 0.0350, 0.9136, 0.1961],
          [0.8171, 0.8297, 0.1995, 0.0871],
          [0.5602, 0.0249, 0.6280, 0.9933]]]])

In [44]:
b.shape

torch.Size([2, 2, 3, 4])

In [43]:
b

tensor([[[[0.0518, 0.3707, 0.6357, 0.5651],
          [0.7455, 0.8993, 0.8996, 0.5205],
          [0.0416, 0.7480, 0.8813, 0.3289]],

         [[0.4246, 0.1962, 0.9842, 0.0630],
          [0.8791, 0.1710, 0.6632, 0.0837],
          [0.3168, 0.9068, 0.7597, 0.6429]]],


        [[[0.2603, 0.9811, 0.4213, 0.9594],
          [0.7628, 0.5062, 0.8340, 0.0782],
          [0.4589, 0.2107, 0.5254, 0.8221]],

         [[0.2604, 0.0350, 0.9136, 0.1961],
          [0.8171, 0.8297, 0.1995, 0.0871],
          [0.5602, 0.0249, 0.6280, 0.9933]]]])

In [46]:
indices=torch.tensor([0,2])
print(torch.index_select(b, 2, indices).shape)
torch.index_select(b, 2, indices)

torch.Size([2, 2, 2, 4])


tensor([[[[0.0518, 0.3707, 0.6357, 0.5651],
          [0.0416, 0.7480, 0.8813, 0.3289]],

         [[0.4246, 0.1962, 0.9842, 0.0630],
          [0.3168, 0.9068, 0.7597, 0.6429]]],


        [[[0.2603, 0.9811, 0.4213, 0.9594],
          [0.4589, 0.2107, 0.5254, 0.8221]],

         [[0.2604, 0.0350, 0.9136, 0.1961],
          [0.5602, 0.0249, 0.6280, 0.9933]]]])

In [47]:
b.shape

torch.Size([2, 2, 3, 4])

In [48]:
b

tensor([[[[0.0518, 0.3707, 0.6357, 0.5651],
          [0.7455, 0.8993, 0.8996, 0.5205],
          [0.0416, 0.7480, 0.8813, 0.3289]],

         [[0.4246, 0.1962, 0.9842, 0.0630],
          [0.8791, 0.1710, 0.6632, 0.0837],
          [0.3168, 0.9068, 0.7597, 0.6429]]],


        [[[0.2603, 0.9811, 0.4213, 0.9594],
          [0.7628, 0.5062, 0.8340, 0.0782],
          [0.4589, 0.2107, 0.5254, 0.8221]],

         [[0.2604, 0.0350, 0.9136, 0.1961],
          [0.8171, 0.8297, 0.1995, 0.0871],
          [0.5602, 0.0249, 0.6280, 0.9933]]]])

In [50]:
indices=torch.LongTensor([1,3])
print(torch.index_select(b,3,indices))
torch.index_select(b, 3, indices)

tensor([[[[0.3707, 0.5651],
          [0.8993, 0.5205],
          [0.7480, 0.3289]],

         [[0.1962, 0.0630],
          [0.1710, 0.0837],
          [0.9068, 0.6429]]],


        [[[0.9811, 0.9594],
          [0.5062, 0.0782],
          [0.2107, 0.8221]],

         [[0.0350, 0.1961],
          [0.8297, 0.0871],
          [0.0249, 0.9933]]]])


tensor([[[[0.3707, 0.5651],
          [0.8993, 0.5205],
          [0.7480, 0.3289]],

         [[0.1962, 0.0630],
          [0.1710, 0.0837],
          [0.9068, 0.6429]]],


        [[[0.9811, 0.9594],
          [0.5062, 0.0782],
          [0.2107, 0.8221]],

         [[0.0350, 0.1961],
          [0.8297, 0.0871],
          [0.0249, 0.9933]]]])

In [52]:
print(b.shape)
b

torch.Size([2, 2, 3, 4])


tensor([[[[0.0518, 0.3707, 0.6357, 0.5651],
          [0.7455, 0.8993, 0.8996, 0.5205],
          [0.0416, 0.7480, 0.8813, 0.3289]],

         [[0.4246, 0.1962, 0.9842, 0.0630],
          [0.8791, 0.1710, 0.6632, 0.0837],
          [0.3168, 0.9068, 0.7597, 0.6429]]],


        [[[0.2603, 0.9811, 0.4213, 0.9594],
          [0.7628, 0.5062, 0.8340, 0.0782],
          [0.4589, 0.2107, 0.5254, 0.8221]],

         [[0.2604, 0.0350, 0.9136, 0.1961],
          [0.8171, 0.8297, 0.1995, 0.0871],
          [0.5602, 0.0249, 0.6280, 0.9933]]]])

In [54]:
torch.index_select(b, 3, torch.LongTensor([1,3]))

tensor([[[[0.3707, 0.5651],
          [0.8993, 0.5205],
          [0.7480, 0.3289]],

         [[0.1962, 0.0630],
          [0.1710, 0.0837],
          [0.9068, 0.6429]]],


        [[[0.9811, 0.9594],
          [0.5062, 0.0782],
          [0.2107, 0.8221]],

         [[0.0350, 0.1961],
          [0.8297, 0.0871],
          [0.0249, 0.9933]]]])

In [58]:
a=torch.IntTensor(4,3,28,28)
a.shape

torch.Size([4, 3, 28, 28])

In [59]:
a=torch.randn(4,3,28,28)
a.shape

torch.Size([4, 3, 28, 28])

In [60]:
a.index_select(2, torch.arange(28)).shape

torch.Size([4, 3, 28, 28])

In [61]:
a.index_select(2, torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

### ...

In [62]:
a.shape

torch.Size([4, 3, 28, 28])

In [63]:
a[...].shape

torch.Size([4, 3, 28, 28])

In [66]:
a[0,...].shape

torch.Size([3, 28, 28])

In [67]:
a[:, 1,...].shape

torch.Size([4, 28, 28])

In [68]:
a[...,:2].shape

torch.Size([4, 3, 28, 2])

# P14. 维度变化1

Operation

View/ reshape 

Squeeze/ unsqueeze 

Transpose/t/permute 

Expand/repeat

## view reshape 

In [69]:
a = torch.rand(4,1,28,28)
a.shape

torch.Size([4, 1, 28, 28])

In [71]:
a_test = a.view(4, 28*28)
print(a.shape)
a_test.shape

torch.Size([4, 1, 28, 28])


torch.Size([4, 784])

In [72]:
a.view(4*28,28).shape

torch.Size([112, 28])

In [73]:
a.view(4*1, 28,28).shape

torch.Size([4, 28, 28])

In [74]:
b = a.view(4, 28*28)
b.shape

torch.Size([4, 784])

important logic bug 

In [76]:
b.view(4,28,28,1).shape  # logic bug

torch.Size([4, 28, 28, 1])

In [ ]:
# b,c,h,w 

# P15. 维度变换_2

unsqueeze 

[-a.dim()-1, a.dim()+1)

squeeze

In [78]:
a.shape

torch.Size([4, 1, 28, 28])

In [79]:
a.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [80]:
a.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [81]:
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

In [82]:
a.unsqueeze(-4).shape

torch.Size([4, 1, 1, 28, 28])

In [ ]:
-5,-4,-3,-2,-1,0,1,2,3,4

4,1,28,28

In [85]:
a= torch.tensor([1.2, 2.3])
print(a.shape)
a.unsqueeze(-1)

torch.Size([2])


tensor([[1.2000],
        [2.3000]])

In [84]:
a.unsqueeze(0)

tensor([[1.2000, 2.3000]])

### for example

In [90]:
b= torch.rand(32)
print(b.shape)
b

torch.Size([32])


tensor([0.4313, 0.6352, 0.4368, 0.4860, 0.7112, 0.6663, 0.3365, 0.6608, 0.9006,
        0.3030, 0.9845, 0.8749, 0.5596, 0.2134, 0.6703, 0.8300, 0.0928, 0.0383,
        0.0503, 0.2575, 0.8429, 0.6148, 0.2683, 0.1907, 0.3970, 0.5759, 0.9688,
        0.9680, 0.5576, 0.8033, 0.9707, 0.2557])

In [91]:
f = torch.rand(4,32,14,14)
b = b.unsqueeze(1)
b.shape

torch.Size([32, 1])

In [92]:
b= b.unsqueeze(2)
b.shape

torch.Size([32, 1, 1])

In [93]:
b =b.unsqueeze(0)
b.shape

torch.Size([1, 32, 1, 1])

In [94]:
f.shape

torch.Size([4, 32, 14, 14])

In [96]:
(f+b).shape

torch.Size([4, 32, 14, 14])

#### squeeze 

In [97]:
b.shape

torch.Size([1, 32, 1, 1])

In [98]:
b.squeeze().shape

torch.Size([32])

In [99]:
b.squeeze(0).shape

torch.Size([32, 1, 1])

In [101]:
b.shape

torch.Size([1, 32, 1, 1])

In [100]:
b.squeeze(-1).shape

torch.Size([1, 32, 1])

In [102]:
b.shape

torch.Size([1, 32, 1, 1])

In [103]:
b.squeeze(1).shape

torch.Size([1, 32, 1, 1])

In [104]:
b.shape

torch.Size([1, 32, 1, 1])

In [105]:
b.squeeze(-4).shape

torch.Size([32, 1, 1])

In [ ]:
这里少了一部分

# P17. 维度变换_4

In [106]:
b.shape

torch.Size([1, 32, 1, 1])

In [107]:
b.repeat(4,32,1,1).shape

torch.Size([4, 1024, 1, 1])

In [108]:
b.repeat(4,1,1,1).shape

torch.Size([4, 32, 1, 1])

In [109]:
b.repeat(4,1,32,32).shape

torch.Size([4, 32, 32, 32])

In [111]:
a=torch.randn(3,4)
a

tensor([[-0.8318,  0.4990, -0.0754,  1.2142],
        [ 0.2975,  0.8674, -0.1151,  0.3024],
        [ 0.6158,  1.9270,  0.0850,  0.1422]])

In [112]:
a.t()

tensor([[-0.8318,  0.2975,  0.6158],
        [ 0.4990,  0.8674,  1.9270],
        [-0.0754, -0.1151,  0.0850],
        [ 1.2142,  0.3024,  0.1422]])

### transpose 

In [114]:
a = torch.randn(4,3,32,32)
a.shape

torch.Size([4, 3, 32, 32])

In [ ]:
b c h w 
b w h c 

b c w h 

before: b c h w 
after:  b c w h 
破坏原来的维度数据 

In [118]:
a1 = a.transpose(1,3).view(4, 3*32*32).view(4,3,32,32)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [116]:
a.shape

torch.Size([4, 3, 32, 32])

In [ ]:
b c h w 
b w h c 

b w h c 

In [119]:
a1 = a.transpose(1,3).contiguous().view(4, 3*32*32).view(4,3,32,32)
a1.shape  # wrong 

torch.Size([4, 3, 32, 32])

In [120]:
a.shape

torch.Size([4, 3, 32, 32])

In [ ]:
4 3 32 32 
4 32 32 3 
4_32_32_3 
4, 32_32_3
4, 32, 32, 3
4, 3, 32,32 

In [122]:
a2 = a.transpose(1,3).contiguous().view(4,32*32*3).view(4, 32, 32,3).transpose(1,3)
a2.shape

torch.Size([4, 3, 32, 32])

In [123]:
a1.shape

torch.Size([4, 3, 32, 32])

In [124]:
a2.shape

torch.Size([4, 3, 32, 32])

In [125]:
torch.all(torch.eq(a,a1))

tensor(False)

In [126]:
torch.all(torch.eq(a,a2))

tensor(True)

In [127]:
a = torch.rand(4,3,28,28)
a.shape

torch.Size([4, 3, 28, 28])

In [128]:
a.transpose(1,3).shape

torch.Size([4, 28, 28, 3])

In [129]:
b = torch.rand(4,3,28,32)
print(b.shape)

b.transpose(1,3).shape

torch.Size([4, 3, 28, 32])


torch.Size([4, 32, 28, 3])

In [130]:
b.transpose(1,3).transpose(1,2).shape

torch.Size([4, 28, 32, 3])

In [ ]:
b c h w 
b h w c 

In [131]:
b.permute(0,2,3,1).shape

torch.Size([4, 28, 32, 3])

少了一部分 

# P17. Broadcasting_2 

In [ ]:
[4,3,32,32]

+[32,32]

+[3,1,1]

+[1,1,1,1]

# P18. 合并与切割_1

cat 

stack 

split

chunk 

### cat 

In [133]:
a = torch.rand(4,32,8)

b = torch.rand(5,32,8)

torch.cat([a,b], dim=0).shape

torch.Size([9, 32, 8])

In [134]:
torch.cat([a,b], dim=1).shape

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 4 and 5 in dimension 0 at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensor.cpp:689

### for example 

In [135]:
a1 = torch.rand(4,3,32,32)
a2 = torch.rand(5,3,32,32)

torch.cat([a1,a2], dim=0).shape

torch.Size([9, 3, 32, 32])

In [136]:
a1.shape

torch.Size([4, 3, 32, 32])

In [137]:
a2 = torch.rand(4,1,32,32)
a2.shape

torch.Size([4, 1, 32, 32])

In [138]:
torch.cat([a1,a2], dim=0).shape

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 3 and 1 in dimension 1 at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensor.cpp:689

In [140]:
a1.shape, a2.shape

(torch.Size([4, 3, 32, 32]), torch.Size([4, 1, 32, 32]))

In [141]:
torch.cat([a1,a2], dim=1).shape

torch.Size([4, 4, 32, 32])

In [142]:
a1 = torch.rand(4,3,16,32)
a2 = torch.rand(4,3,16,32)

In [143]:
torch.cat([a1,a2], dim=2).shape

torch.Size([4, 3, 32, 32])

### stack 

create new dim 

In [144]:
a1.shape, a2.shape

(torch.Size([4, 3, 16, 32]), torch.Size([4, 3, 16, 32]))

In [146]:
torch.cat([a1,a2], dim=2).shape

torch.Size([4, 3, 32, 32])

In [148]:
a1.shape, a2.shape

(torch.Size([4, 3, 16, 32]), torch.Size([4, 3, 16, 32]))

In [147]:
torch.stack([a1,a2], dim=2).shape

torch.Size([4, 3, 2, 16, 32])

In [149]:
a = torch.rand(32,8)
b = torch.rand(32,8)

a.shape, b.shape

(torch.Size([32, 8]), torch.Size([32, 8]))

In [150]:
torch.stack([a,b], dim=0).shape

torch.Size([2, 32, 8])

#### cat v.s. stack 

In [2]:
import torch 

a = torch.rand(32,8)
a.shape

torch.Size([32, 8])

In [4]:
b = torch.rand([30,8])
b.shape

torch.Size([30, 8])

In [5]:
torch.stack([a,b], dim=0)

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 32 and 30 in dimension 1 at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensor.cpp:689

In [6]:
torch.cat([a,b], dim=0).shape

torch.Size([62, 8])

# P19. 合并与切割_2

split : by len 

In [7]:
b = torch.rand(32,8)
a.shape

torch.Size([32, 8])

In [8]:
c = torch.stack([a,b], dim=0)
c.shape

torch.Size([2, 32, 8])

In [9]:
aa, bb = c.split([1,1], dim=0)
aa.shape, bb.shape

(torch.Size([1, 32, 8]), torch.Size([1, 32, 8]))

In [10]:
c.shape

torch.Size([2, 32, 8])

In [11]:
aa, bb = c.split([1,1], dim=0)
aa.shape, bb.shape

(torch.Size([1, 32, 8]), torch.Size([1, 32, 8]))

In [12]:
c.shape 

torch.Size([2, 32, 8])

In [14]:
aa, bb = c.split(1, dim=0)
aa.shape, bb.shape 

(torch.Size([1, 32, 8]), torch.Size([1, 32, 8]))

In [15]:
aa, bb = c.split(2, dim=0)
aa.shape, bb.shape

ValueError: not enough values to unpack (expected 2, got 1)

### chunk: by num 

In [16]:
c.shape 

torch.Size([2, 32, 8])

In [18]:
aa, bb = c.chunk(2, dim=0)  # 2//2 
aa.shape, bb.shape 

(torch.Size([1, 32, 8]), torch.Size([1, 32, 8]))

# P  维度变换_3 

expand  扩展一次

repeat  增加数据 

In [3]:
import torch
a = torch.rand(4,32,14,14)
a.shape

torch.Size([4, 32, 14, 14])

In [4]:
b = torch.rand(1,32,1,1)
b.shape 

torch.Size([1, 32, 1, 1])

In [5]:
b.expand(4,32,14,14).shape 

torch.Size([4, 32, 14, 14])

In [6]:
b.expand(-1,32,2,-1).shape 

torch.Size([1, 32, 2, 1])

In [7]:
b.shape 

torch.Size([1, 32, 1, 1])

In [8]:
b.repeat(4,32,1,1).shape

torch.Size([4, 1024, 1, 1])

In [9]:
b.repeat(4,1,1,1).shape 

torch.Size([4, 32, 1, 1])

In [10]:
b.repeat(4,1,32,32).shape

torch.Size([4, 32, 32, 32])

# P17. 维度变化_4 

In [11]:
b.shape

torch.Size([1, 32, 1, 1])

In [12]:
b.t()  # 痣适合 2 维数据

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 4D

In [14]:
a = torch.randn(3,4)
print(a.shape)
a

torch.Size([3, 4])


tensor([[-0.2328, -0.8394, -1.3142,  0.0507],
        [-0.1075,  1.2343, -1.2747,  0.8819],
        [-0.8704, -0.8008,  0.1237,  1.3115]])

In [15]:
a.t()

tensor([[-0.2328, -0.1075, -0.8704],
        [-0.8394,  1.2343, -0.8008],
        [-1.3142, -1.2747,  0.1237],
        [ 0.0507,  0.8819,  1.3115]])

In [18]:
a = torch.rand(4,3,32,32)
a.shape 

torch.Size([4, 3, 32, 32])

In [ ]:
b c h w 
b w h c 
b, w*h*c 

4, 3 ,32, 32 
4, 32, 32, 3 

4, 32*32*3
4, 3, 32, 32 


In [19]:
a1 = a.transpose(1,3).view(4, 3*32*32).view(4,3,32,32)
a1.shape 

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [20]:
a.shape 

torch.Size([4, 3, 32, 32])

In [22]:
a1 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,3,32,32)
a1.shape

torch.Size([4, 3, 32, 32])

In [27]:
a2 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,32,32,3).transpose(1,3)
a2.shape

torch.Size([4, 3, 32, 32])

In [24]:
a1.shape, a2.shape 

(torch.Size([4, 3, 32, 32]), torch.Size([4, 32, 32, 3]))

In [25]:
torch.all(torch.eq(a,a1))

tensor(False)

In [28]:
torch.all(torch.eq(a,a2))

tensor(True)

In [29]:
b.shape

torch.Size([1, 32, 1, 1])

In [30]:
b.permute(0,2,3,1).shape

torch.Size([1, 1, 1, 32])

# P。 Broadcast

In [32]:
a = torch.tensor([4,32,8])
b= torch.tensor([5])

a,b

(tensor([ 4, 32,  8]), tensor([5]))

In [33]:
a+b

tensor([ 9, 37, 13])

In [35]:
a = torch.rand(4,3,32,32)
b = torch.rand(32,32)
(a+b).shape

torch.Size([4, 3, 32, 32])

In [36]:
b= torch.rand(3,1,1)
(a+b).shape

torch.Size([4, 3, 32, 32])

In [37]:
b = torch.rand(1,1,1,1)
(a+b).shape

torch.Size([4, 3, 32, 32])

In [1]:
import torch 

In [3]:
a= torch.rand(4,10)
a

tensor([[0.9462, 0.4326, 0.5675, 0.7065, 0.5205, 0.7218, 0.1533, 0.6732, 0.3976,
         0.8211],
        [0.6068, 0.1998, 0.7678, 0.8257, 0.9298, 0.2710, 0.4480, 0.3220, 0.8463,
         0.4049],
        [0.0377, 0.6617, 0.2221, 0.3258, 0.2728, 0.7788, 0.9219, 0.0161, 0.2530,
         0.2468],
        [0.1885, 0.4459, 0.8358, 0.6339, 0.5881, 0.2123, 0.6729, 0.5201, 0.7058,
         0.9495]])

In [5]:
a.max(dim=0)

torch.return_types.max(
values=tensor([0.9462, 0.6617, 0.8358, 0.8257, 0.9298, 0.7788, 0.9219, 0.6732, 0.8463,
        0.9495]),
indices=tensor([0, 2, 3, 1, 1, 2, 2, 0, 1, 3]))

In [6]:
a.max(dim=1)

torch.return_types.max(
values=tensor([0.9462, 0.9298, 0.9219, 0.9495]),
indices=tensor([0, 4, 6, 9]))

In [7]:
a.max(dim=0, keepdim=True)

torch.return_types.max(
values=tensor([[0.9462, 0.6617, 0.8358, 0.8257, 0.9298, 0.7788, 0.9219, 0.6732, 0.8463,
         0.9495]]),
indices=tensor([[0, 2, 3, 1, 1, 2, 2, 0, 1, 3]]))

In [9]:
a.max(dim=1, keepdim=True)

torch.return_types.max(
values=tensor([[0.9462],
        [0.9298],
        [0.9219],
        [0.9495]]),
indices=tensor([[0],
        [4],
        [6],
        [9]]))

In [10]:
print(a.shape)
a

torch.Size([4, 10])


tensor([[0.9462, 0.4326, 0.5675, 0.7065, 0.5205, 0.7218, 0.1533, 0.6732, 0.3976,
         0.8211],
        [0.6068, 0.1998, 0.7678, 0.8257, 0.9298, 0.2710, 0.4480, 0.3220, 0.8463,
         0.4049],
        [0.0377, 0.6617, 0.2221, 0.3258, 0.2728, 0.7788, 0.9219, 0.0161, 0.2530,
         0.2468],
        [0.1885, 0.4459, 0.8358, 0.6339, 0.5881, 0.2123, 0.6729, 0.5201, 0.7058,
         0.9495]])

In [11]:
a.topk(3, dim=1)

torch.return_types.topk(
values=tensor([[0.9462, 0.8211, 0.7218],
        [0.9298, 0.8463, 0.8257],
        [0.9219, 0.7788, 0.6617],
        [0.9495, 0.8358, 0.7058]]),
indices=tensor([[0, 9, 5],
        [4, 8, 3],
        [6, 5, 1],
        [9, 2, 8]]))

In [12]:
a.topk(3, dim=1, largest = False)

torch.return_types.topk(
values=tensor([[0.1533, 0.3976, 0.4326],
        [0.1998, 0.2710, 0.3220],
        [0.0161, 0.0377, 0.2221],
        [0.1885, 0.2123, 0.4459]]),
indices=tensor([[6, 8, 1],
        [1, 5, 7],
        [7, 0, 2],
        [0, 5, 1]]))

In [13]:
a.kthvalue(8, dim=1)

torch.return_types.kthvalue(
values=tensor([0.7218, 0.8257, 0.6617, 0.7058]),
indices=tensor([5, 3, 1, 8]))

In [14]:
a.kthvalue(3)

torch.return_types.kthvalue(
values=tensor([0.4326, 0.3220, 0.2221, 0.4459]),
indices=tensor([1, 7, 2, 1]))

In [15]:
a.kthvalue(3, dim=1)

torch.return_types.kthvalue(
values=tensor([0.4326, 0.3220, 0.2221, 0.4459]),
indices=tensor([1, 7, 2, 1]))

In [19]:
a.kthvalue(3, dim=0)

torch.return_types.kthvalue(
values=tensor([0.6068, 0.4459, 0.7678, 0.7065, 0.5881, 0.7218, 0.6729, 0.5201, 0.7058,
        0.8211]),
indices=tensor([1, 3, 1, 0, 3, 0, 3, 3, 3, 0]))