# P20-22 张量高阶操作·

# P20. 基本运算

add/ minus/ multiply/ divide

matmul

pow

sqrt/rsqrt

round

## basic 

In [1]:
import torch

In [2]:
a = torch.rand(3,4)
a

tensor([[0.9981, 0.9158, 0.9901, 0.5383],
        [0.1640, 0.6093, 0.1056, 0.8836],
        [0.2383, 0.4925, 0.1617, 0.7476]])

In [4]:
b = torch.rand(4)
b

tensor([0.4891, 0.4565, 0.8818, 0.5622])

In [5]:
a+b

tensor([[1.4872, 1.3723, 1.8719, 1.1005],
        [0.6530, 1.0658, 0.9874, 1.4458],
        [0.7273, 0.9490, 1.0435, 1.3098]])

In [6]:
torch.add(a,b)

tensor([[1.4872, 1.3723, 1.8719, 1.1005],
        [0.6530, 1.0658, 0.9874, 1.4458],
        [0.7273, 0.9490, 1.0435, 1.3098]])

In [7]:
torch.all(torch.eq(a-b, torch.sub(a,b)))

tensor(True)

In [8]:
torch.all(torch.eq(a*b, torch.mul(a,b)))

tensor(True)

In [9]:
torch.all(torch.eq(a/b, torch.div(a,b)))

tensor(True)

In [12]:
c = torch.rand(3,4)
d = torch.rand(3)

c, d

(tensor([[0.9846, 0.0094, 0.6117, 0.2419],
         [0.8305, 0.0737, 0.3318, 0.3713],
         [0.4175, 0.3625, 0.0459, 0.3376]]), tensor([0.1014, 0.5654, 0.6647]))

In [14]:
c+d

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

## matmul 矩阵相乘

matmul:
    
Torch.mm  # only for 2d 

Torch.matmul@ 

In [15]:
a = torch.tensor([[3,3],
                 [3,3]], dtype=torch.float)

a

tensor([[3., 3.],
        [3., 3.]])

In [16]:
b = torch.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [19]:
print(a)

print(b)

tensor([[3., 3.],
        [3., 3.]])
tensor([[1., 1.],
        [1., 1.]])


In [17]:
torch.mm(a,b)

tensor([[6., 6.],
        [6., 6.]])

In [20]:
torch.matmul(a,b)

tensor([[6., 6.],
        [6., 6.]])

In [21]:
a@b

tensor([[6., 6.],
        [6., 6.]])

#### an example 

In [22]:
a = torch.rand(4, 784)
x = torch.rand(4,784)
w = torch.rand(512, 784)

In [23]:
(x@w.t()).shape

torch.Size([4, 512])

### > 2d tensor matmul?

In [25]:
a = torch.rand(4,3,28,64)
b = torch.rand(4,3,64,32)

torch.mm(a,b).shape

RuntimeError: matrices expected, got 4D, 4D tensors at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensorMath.cpp:192

In [27]:
a.shape, b.shape 

(torch.Size([4, 3, 28, 64]), torch.Size([4, 3, 64, 32]))

In [26]:
torch.matmul(a,b).shape

torch.Size([4, 3, 28, 32])

In [29]:
b = torch.rand(4,1,64,32)
a.shape, b.shape

(torch.Size([4, 3, 28, 64]), torch.Size([4, 1, 64, 32]))

In [30]:
torch.matmul(a,b).shape

torch.Size([4, 3, 28, 32])

In [31]:
b = torch.rand(4, 64,32)
a.shape, b.shape 

(torch.Size([4, 3, 28, 64]), torch.Size([4, 64, 32]))

In [32]:
torch.matmul(a,b).shape

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

### power

In [33]:
a = torch.full([2,2],3)
a

tensor([[3., 3.],
        [3., 3.]])

In [34]:
a.pow(2)

tensor([[9., 9.],
        [9., 9.]])

In [35]:
a

tensor([[3., 3.],
        [3., 3.]])

In [36]:
a**2

tensor([[9., 9.],
        [9., 9.]])

In [38]:
aa = a**2
aa

tensor([[9., 9.],
        [9., 9.]])

In [39]:
aa.sqrt()

tensor([[3., 3.],
        [3., 3.]])

In [40]:
aa.rsqrt()  # 1/3

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333]])

In [41]:
aa**(0.5)

tensor([[3., 3.],
        [3., 3.]])

### Approximation 

floor()  ceil()

round()

trunc().     frac()

In [43]:
a = torch.tensor(3.14)
a

tensor(3.1400)

In [45]:
a.floor(),  a.ceil(),  a.trunc(), a.frac()

(tensor(3.), tensor(4.), tensor(3.), tensor(0.1400))

In [46]:
a = torch.tensor(3.499)
a

tensor(3.4990)

In [47]:
a.round()

tensor(3.)

In [48]:
a = torch.tensor(3.5)
a.round()

tensor(4.)

### clamp 

gradient clipping 

(min)

(min, max)

In [50]:
grad = torch.rand(2,3)*15 
grad

tensor([[ 2.5246, 12.2040, 11.6068],
        [ 5.5253,  7.3290, 11.4006]])

In [51]:
grad.max()

tensor(12.2040)

In [52]:
grad.median()

tensor(7.3290)

In [53]:
grad

tensor([[ 2.5246, 12.2040, 11.6068],
        [ 5.5253,  7.3290, 11.4006]])

In [55]:
grad.clamp(10)

tensor([[10.0000, 12.2040, 11.6068],
        [10.0000, 10.0000, 11.4006]])

In [56]:
grad

tensor([[ 2.5246, 12.2040, 11.6068],
        [ 5.5253,  7.3290, 11.4006]])

In [57]:
grad.clamp(0,10)

tensor([[ 2.5246, 10.0000, 10.0000],
        [ 5.5253,  7.3290, 10.0000]])

# P21. 数据统计_2 

argmax , argmin 

dim, keepdim




In [59]:
a= torch.arange(8).view(1,2,4)
a

tensor([[[0, 1, 2, 3],
         [4, 5, 6, 7]]])

In [60]:
a.argmax()

tensor(7)

In [61]:
a.argmin()

tensor(0)

In [62]:
a = torch.rand(2,3,4)
a

tensor([[[0.6098, 0.5108, 0.4934, 0.4223],
         [0.3037, 0.3621, 0.9246, 0.7067],
         [0.8663, 0.1978, 0.0974, 0.0544]],

        [[0.2961, 0.1226, 0.3548, 0.4830],
         [0.6224, 0.3387, 0.0469, 0.4735],
         [0.5121, 0.6054, 0.5980, 0.9719]]])

In [63]:
a.argmax()  # 0-23 max is the last one 

tensor(23)

In [64]:
a = torch.rand(4,10)
a

tensor([[0.0327, 0.1696, 0.5711, 0.9897, 0.6627, 0.6835, 0.2557, 0.2206, 0.7909,
         0.7196],
        [0.2972, 0.4013, 0.4320, 0.9516, 0.2819, 0.0323, 0.1748, 0.5102, 0.6809,
         0.0625],
        [0.7790, 0.4353, 0.6950, 0.6190, 0.9151, 0.5384, 0.0563, 0.3027, 0.9805,
         0.0409],
        [0.2927, 0.8096, 0.5319, 0.6088, 0.6093, 0.5416, 0.4682, 0.5819, 0.3838,
         0.4596]])

In [65]:
a[0]

tensor([0.0327, 0.1696, 0.5711, 0.9897, 0.6627, 0.6835, 0.2557, 0.2206, 0.7909,
        0.7196])

In [66]:
a.argmax()

tensor(3)

In [67]:
a.shape

torch.Size([4, 10])

In [ ]:
a.argmax()

In [69]:
print(a)
a.shape


tensor([[0.0327, 0.1696, 0.5711, 0.9897, 0.6627, 0.6835, 0.2557, 0.2206, 0.7909,
         0.7196],
        [0.2972, 0.4013, 0.4320, 0.9516, 0.2819, 0.0323, 0.1748, 0.5102, 0.6809,
         0.0625],
        [0.7790, 0.4353, 0.6950, 0.6190, 0.9151, 0.5384, 0.0563, 0.3027, 0.9805,
         0.0409],
        [0.2927, 0.8096, 0.5319, 0.6088, 0.6093, 0.5416, 0.4682, 0.5819, 0.3838,
         0.4596]])


torch.Size([4, 10])

In [70]:
a.argmax(dim=1)

tensor([3, 3, 8, 1])

### dim, keepdim 

In [72]:
a

tensor([[0.0327, 0.1696, 0.5711, 0.9897, 0.6627, 0.6835, 0.2557, 0.2206, 0.7909,
         0.7196],
        [0.2972, 0.4013, 0.4320, 0.9516, 0.2819, 0.0323, 0.1748, 0.5102, 0.6809,
         0.0625],
        [0.7790, 0.4353, 0.6950, 0.6190, 0.9151, 0.5384, 0.0563, 0.3027, 0.9805,
         0.0409],
        [0.2927, 0.8096, 0.5319, 0.6088, 0.6093, 0.5416, 0.4682, 0.5819, 0.3838,
         0.4596]])

In [73]:
a.max(dim=1)

torch.return_types.max(
values=tensor([0.9897, 0.9516, 0.9805, 0.8096]),
indices=tensor([3, 3, 8, 1]))

In [74]:
a.argmax(dim=1)

tensor([3, 3, 8, 1])

In [75]:
a.max(dim=1, keepdim=True)

torch.return_types.max(
values=tensor([[0.9897],
        [0.9516],
        [0.9805],
        [0.8096]]),
indices=tensor([[3],
        [3],
        [8],
        [1]]))

In [76]:
a.argmax(dim=1, keepdim=True)

tensor([[3],
        [3],
        [8],
        [1]])

### Top-k or k-th 

topk
    largets
    
kthvalue 

In [80]:
print(a.shape)
a

torch.Size([4, 10])


tensor([[0.0327, 0.1696, 0.5711, 0.9897, 0.6627, 0.6835, 0.2557, 0.2206, 0.7909,
         0.7196],
        [0.2972, 0.4013, 0.4320, 0.9516, 0.2819, 0.0323, 0.1748, 0.5102, 0.6809,
         0.0625],
        [0.7790, 0.4353, 0.6950, 0.6190, 0.9151, 0.5384, 0.0563, 0.3027, 0.9805,
         0.0409],
        [0.2927, 0.8096, 0.5319, 0.6088, 0.6093, 0.5416, 0.4682, 0.5819, 0.3838,
         0.4596]])

In [79]:
a.topk(3, dim=1)

torch.return_types.topk(
values=tensor([[0.9897, 0.7909, 0.7196],
        [0.9516, 0.6809, 0.5102],
        [0.9805, 0.9151, 0.7790],
        [0.8096, 0.6093, 0.6088]]),
indices=tensor([[3, 8, 9],
        [3, 8, 7],
        [8, 4, 0],
        [1, 4, 3]]))

In [81]:
a.topk(3, dim=1, largest=False)

torch.return_types.topk(
values=tensor([[0.0327, 0.1696, 0.2206],
        [0.0323, 0.0625, 0.1748],
        [0.0409, 0.0563, 0.3027],
        [0.2927, 0.3838, 0.4596]]),
indices=tensor([[0, 1, 7],
        [5, 9, 6],
        [9, 6, 7],
        [0, 8, 9]]))

In [83]:
print(a.shape)
a

torch.Size([4, 10])


tensor([[0.0327, 0.1696, 0.5711, 0.9897, 0.6627, 0.6835, 0.2557, 0.2206, 0.7909,
         0.7196],
        [0.2972, 0.4013, 0.4320, 0.9516, 0.2819, 0.0323, 0.1748, 0.5102, 0.6809,
         0.0625],
        [0.7790, 0.4353, 0.6950, 0.6190, 0.9151, 0.5384, 0.0563, 0.3027, 0.9805,
         0.0409],
        [0.2927, 0.8096, 0.5319, 0.6088, 0.6093, 0.5416, 0.4682, 0.5819, 0.3838,
         0.4596]])

In [85]:
# 每一行中 第八个小的是什么
a.kthvalue(8, dim=1) # 第八小的是什么

torch.return_types.kthvalue(
values=tensor([0.7196, 0.5102, 0.7790, 0.6088]),
indices=tensor([9, 7, 0, 3]))

In [86]:
a.kthvalue(3)

torch.return_types.kthvalue(
values=tensor([0.2206, 0.1748, 0.3027, 0.4596]),
indices=tensor([7, 6, 7, 9]))

### compare 

   > >= < <= != ==
   
torch.eq(a,b)

In [87]:
torch.equal(a,b)  

# return True False 

False

# P22 高阶OP 

where

gather 

In [ ]:
torch.where(condition, x, y) -> Tensor 

In [88]:
cond =torch.tensor([[0.6769, 0.7271],
                   [0.8884, 0.4163]])

cond

tensor([[0.6769, 0.7271],
        [0.8884, 0.4163]])

In [90]:
a = torch.full([2,2], 0)
a

tensor([[0., 0.],
        [0., 0.]])

In [92]:
b = torch.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [93]:
torch.where(cond>0.5, a,b)

tensor([[0., 0.],
        [0., 1.]])

torch.gather(input, dim, index, out=None)-> Tensor 

没有看 gather 